from bug import KotlinBug
import categories as ct
import characteristics as pc
import symptoms as sy
import root_causes as rc


kotlin_iter1 = [
    KotlinBug(
        "1.KT-1934",
        [pc.StandardFeatures(pc.Inheritance())],
        False,
        sy.Runtime(sy.WrongMethodCalled()),
        rc.MissingCase(),
        ct.Declarations()
    ),
    KotlinBug(
        "2.KT-4814",
        [pc.StandardFeatures(pc.ArithmeticExpressions())],
        False,
        sy.Runtime(sy.VerifyError()),
        rc.MissingCase(),
        ct.TypeExpression()
    ),
    KotlinBug(
        "3.KT-42175",
        [
            pc.HigherOrderProgramming(pc.Lambdas()),
            pc.StandardLibrary(pc.Collections()),
            pc.StandardFeatures(pc.This())
        ],
        True,
        sy.CompileTimeError(),
        rc.MissingCase(),
        ct.Inference()  # "type variable substitution"
    ),
    KotlinBug(
        "4.KT-10244",
        [pc.TypeInference(pc.FlowTyping()),
         pc.SpecialTypes(pc.IntersectionTypes()),
         pc.StandardFeatures(pc.Conditionals())],
        False,
        sy.InternalCompilerError(),
        rc.MissingCase(),
        ct.Declarations()
    ),
    KotlinBug(
        "5.KT-10472",
        [pc.Overloading(), pc.StandardFeatures(pc.Varargs()),
         pc.ParametricPolymorphism(pc.ParameterizedClasses(),
                                   pc.ParameterizedFunctions()),
         pc.SpecialTypes(pc.ParameterizedTypes())],
        True,
        sy.Runtime(sy.NullPointerException()),
        rc.MissingCase(),
        ct.Resolution()
    ),
    KotlinBug(
        "6.KT-7485",
        [pc.ParametricPolymorphism(pc.BoundedPolymorphism(pc.Where()),
                                   pc.ParameterizedFunctions(),
                                   pc.ParameterizedClasses()),
         pc.SpecialTypes(pc.Nullables()),
         pc.Subtyping()],
        False,
        sy.Runtime(sy.NullPointerException()),
        rc.IncorrectComputation(),
        ct.SubtypingRelated()
    ),
    KotlinBug(
        "7.KT-23748",
        [pc.ParametricPolymorphism(pc.ParameterizedFunctions),
         pc.Subtyping(),
         pc.SpecialTypes(pc.Nullables()),
         pc.SpecialLanguageFeatures(pc.ElvisOperator())],
        True,
        sy.CompileTimeError(),
        rc.DesignIssue(),
        ct.Inference()  # constraint solving
    ),
    KotlinBug(
        "8.KT-22728",
        [pc.HigherOrderProgramming(pc.Lambdas(), pc.ExtensionFunctions()),
         pc.SpecialLanguageFeatures(pc.Typealias()),
         pc.StandardFeatures(pc.MultiplePackages(), pc.This()),
         pc.SpecialTypes(pc.FunctionTypes())],
        True,
        sy.CompileTimeError(),
        rc.WrongParams(),
        ct.Misc()  # mechanics
    ),
    KotlinBug(
        "9.KT-10711",
        [pc.ParametricPolymorphism(pc.ParameterizedFunctions()),
         pc.StandardLibrary(pc.Collections()),
         pc.HigherOrderProgramming(pc.FunctionReferences())],
        True,
        sy.CompileTimeError(),
        rc.MissingCase(),
        ct.Inference(),  # constraint solving
    ),
    KotlinBug(
        "10.KT-37249",
        [pc.StandardFeatures(pc.Conditionals(), pc.TryCatch()),
         pc.HigherOrderProgramming(pc.Lambdas())],
        True,
        sy.CompileTimeError(),
        rc.InsufficientFunctionality(),
        ct.Inference()  # constraint solving
    ),
    KotlinBug(
        "11.KT-11468",
        [pc.ParametricPolymorphism(pc.ParameterizedClasses(),
                                   pc.Variance(pc.DeclVariance())),
         pc.SpecialTypes(pc.ParameterizedTypes()),
         pc.Subtyping()],
        True,
        sy.InternalCompilerError(),
        rc.DesignIssue(),
        ct.SubtypingRelated()
    ),
    KotlinBug(
        "12.KT-6014",
        [pc.Overriding(), pc.StandardFeatures(pc.Inheritance()),
         pc.SpecialLanguageFeatures(pc.Delegation())],
        True,
        sy.CompileTimeError(),
        rc.IncorrectComputation(),
        ct.Resolution()
    ),
    KotlinBug(
        "13.KT-12044",
        [pc.StandardFeatures(pc.Conditionals()),
         pc.SpecialLanguageFeatures(pc.PropertyReference())],
        True,
        sy.CompileTimeError(),
        rc.WrongParams(),
        ct.Resolution()
    ),
    KotlinBug(
        "14.KT-4334",
        [pc.HigherOrderProgramming(pc.Lambdas()),
         pc.StandardFeatures(pc.Loops())],
        False,
        sy.InternalCompilerError(),
        rc.MissingCase(),
        ct.Misc()
    ),
    KotlinBug(
        "15.KT-32184",
        [pc.HigherOrderProgramming(pc.Lambdas()),
         pc.SpecialLanguageFeatures(pc.DataClasses())],
        True,
        sy.InternalCompilerError(),
        rc.WrongParams(),
        ct.Resolution()
    ),
    KotlinBug(
        "16.KT-10197",
        [pc.Overriding(),
         pc.StandardFeatures(pc.Inheritance()),
         pc.SpecialLanguageFeatures(pc.Delegation())],
        False,
        sy.Runtime(sy.AbstractMethodError()),
        rc.MissingCase(),
        ct.Declarations(),
    ),
    KotlinBug(
        "17.KT-41693",
        [pc.StandardFeatures(pc.Conditionals(), pc.MultiplePackages()),
         pc.SpecialTypes(pc.FlexibleTypes()),
         pc.JavaInterop()],
        True,
        sy.Runtime(sy.NullPointerException()),
        rc.MissingCase(),
        ct.Approximation()
    ),
    KotlinBug(
        "18.KT-44420",
        [pc.SpecialTypes(pc.FlexibleTypes()),
         pc.StandardLibrary(pc.Collections()),
         pc.TypeInference(pc.VarTypeInference()),
         pc.JavaInterop()],
        True,
        sy.CompileTimeError(),
        rc.MissingCase(),
        ct.Approximation(),
    ),
    KotlinBug(
        "19.KT-35602",
        [pc.ParametricPolymorphism(pc.ParameterizedClasses(),
                                   pc.BoundedPolymorphism(pc.FBounded()),
                                   pc.Variance(pc.UseVariance())),
         pc.SpecialLanguageFeatures(pc.NullAssertion())],
        True,
        sy.CompileTimeError(),
        rc.MissingCase(),
        ct.Approximation()
    ),
    KotlinBug(
        "20.KT-6992",
        [pc.Overloading(),
         pc.ParametricPolymorphism(pc.ParameterizedClasses()),
         pc.SpecialLanguageFeatures(pc.Delegation()),
         pc.StandardFeatures(pc.This())],
        False,
        sy.MisleadingReport(),
        rc.MissingCase(),
        ct.Resolution()
    )
]
