# pylint: disable=protected-access,too-many-instance-attributes,too-many-locals
# pylint: disable=too-many-statements
import re
from collections import OrderedDict


import src.utils as ut
from src.ir import ast, java_types as jt, types as tp, type_utils as tu
from src.ir.context import get_decl
from src.transformations.base import change_namespace
from src.translators.base import BaseTranslator


PRIMITIVES_TO_BOXED = {
    'boolean': 'Boolean',
    'byte': 'Byte',
    'char': 'Character',
    'short': 'Short',
    'int': 'Integer',
    'long': 'Long',
    'float': 'Float',
    'double': 'Double',
    'void': 'Void',
}


def append_to(visit):
    """There are three scenarios:

    1. The node is the main function => set _main_method
    2. The node is a top level function or variable declaration => append the
        result to _main_children (nodes to declared static in Main class)
    3. All other nodes just append them to _children_res

    We also use this function to set _nodes_stack
    """
    def inner(self, node):
        self._nodes_stack.append(node)
        res = visit(self, node)
        self._nodes_stack.pop()
        if (self._namespace == ast.GLOBAL_NAMESPACE and
                isinstance(node, ast.FunctionDeclaration) and
                node.name == "main"):
            # If we want to run the program we must replace main() with
            # main(String[] args)
            self._main_method = res
        elif (self._namespace == ast.GLOBAL_NAMESPACE and
                isinstance(
                    node, (ast.VariableDeclaration, ast.FunctionDeclaration))):
            self._main_children.append(res)
        else:
            self._children_res.append(res)
    return inner


class JavaTranslator(BaseTranslator):

    filename = "Main.java"
    incorrect_filename = "Incorrect.java"
    executable = "Main.jar"
    ident_value = " "

    def __init__(self, package=None, options={}):
        super().__init__(package, options)
        self._children_res = []
        self.ident = 0
        self.context = None
        self.types = []
        self._generator = None
        self._cast_number = False
        # Keep track if a block is in a function that has non-void return type
        self.is_func_non_void_block = False

        # Keep track if a block is in a function that is a nested function
        self.is_nested_func_block = False

        # In Java the format of smart cast is the following:
        # ((variable instanceof Type new_var_name) ? new_var_name : foo)
        # To mitigate this issue we keep the variables that we smart cast in
        # a stack. Finally, when we reference a variable inside a conditional,
        # add the suffix _is in variable's name.
        # Example:
        # ((v instanceof Foo v_is) ? v_is : bar)
        # NOTE we currently handle only Variable objects
        self._visit_is_stack = [None]

        self._namespace: tuple = ast.GLOBAL_NAMESPACE
        # We have to add all non-class declarations top-level declarations
        # into a Main static class. Moreover, they should be static and get
        # accessed with `Main.` prefix.
        self._main_children = []
        # main method should be declared public static void, it should be the
        # last element of Main's block.
        self._main_method = ""

        # We need the following state vars to support blocks inside conditions.
        # In groovy the `{ ... }` is a closure. Hence, if we have a Block
        # inside a condition it means we have a closure, thus we must call it
        # immediately `()`.
        self._inside_is = False
        self._inside_is_function = False

        # A set of numbers where numbers is the number of type parameters that
        # an interface for a function should have.
        # TODO pass it as option, or produce the list during the AST traverse
        self._function_interfaces = {0,1,2,3}

        # We need nodes_stack to set semicolons when needed.
        # For instance, in visit_func_call we use a semicolon only if parent
        # node is a block.
        self._nodes_stack = [None]

        # Counter for temporary variables generated by the translator.
        self._x_counter = 0

        # A stack of tuples with expressions and their types provided by smart
        # casts.
        self.smart_casts = []

    def _reset_state(self):
        # Clear the state
        self.types = []
        self._main_method = ""
        self._main_children = []
        self._inside_is = False
        self._inside_is_function = False
        self.context = None
        self._cast_number = False
        self.ident = 0
        self.is_func_non_void_block = False
        self.is_nested_func_block = False
        self._namespace = ast.GLOBAL_NAMESPACE
        self._children_res = []
        self._function_interfaces = {0,1,2,3}
        self._nodes_stack = [None]
        self._visit_is_stack = [None]
        self._x_counter = 0
        self.smart_casts = []

    def get_ident(self, extra=0, old_ident=None):
        if old_ident:
            return old_ident * self.ident_value
        return (self.ident + extra) * self.ident_value

    @staticmethod
    def get_filename():
        return JavaTranslator.filename

    @staticmethod
    def get_incorrect_filename():
        return JavaTranslator.incorrect_filename

    def type_arg2str(self, t_arg):
        if not t_arg.is_wildcard():
            return self.get_type_name(t_arg, True, True)
        if t_arg.is_invariant():
            return "?"
        elif t_arg.is_covariant():
            return "? extends " + self.get_type_name(t_arg.bound, True, True)
        else:
            return "? super " + self.get_type_name(t_arg.bound, True, True)

    def get_type_name(self, t, get_boxed_void=False, box=False):
        if t.is_wildcard():
            t = t.get_bound_rec()
            return self.get_type_name(t, get_boxed_void, box)
        t_constructor = getattr(t, 't_constructor', None)
        if not t_constructor:
            if get_boxed_void and isinstance(t, jt.VoidType):
                return "Void"
            if box:
                return PRIMITIVES_TO_BOXED.get(t.get_name(), t.get_name())
            return t.get_name()
        if isinstance(t_constructor, jt.ArrayType):
            return "{}[]".format(self.get_type_name(t.type_args[0], False, True))
        return "{}<{}>".format(t.name, ", ".join([self.type_arg2str(ta)
                                                  for ta in t.type_args]))

    def pop_children_res(self, children):
        len_c = len(children)
        if not len_c:
            return []
        res = self._children_res[-len_c:]
        self._children_res = self._children_res[:-len_c]
        return res

    def _get_main_prefix(self, decl_type, name):
        ns_decls = list(self.context.get_namespaces_decls(
            self._namespace, name, decl_type))
        if len(ns_decls) == 1 and ns_decls[0][0][:-1] == ast.GLOBAL_NAMESPACE:
            if not self._visit_is_stack.count(name):
                return "Main."
        return ""

    def _get_functional_interfaces(self):
        """It produces the required functional interfaces.
        For each number x in _function_interfaces it creates FunctionX+1.
        The last type argument is used for the return type.
        """
        res = ""
        template = "interface Function{}<{}> {{\n{}public {} apply({});\n}}\n\n"
        for number in self._function_interfaces:
            type_params = ", ".join(
                ["A" + str(i + 1) if i < number else "R"
                 for i in range(0, number + 1)]
            )
            res += template.format(
                number,
                type_params,
                2 * self.ident_value,
                "R",
                ", ".join(["A" + str(i + 1) + " a" + str(i + 1)
                          for i in range(0, number)]),
            )
        res = "\n\n" + res if res != "" else ""
        return res

    def _parent_is_block(self):
        # The second node is the parent node
        return isinstance(self._nodes_stack[-2], ast.Block)

    def _parent_is_function(self):
        # The second node is the parent node
        return isinstance(self._nodes_stack[-2], (ast.Lambda,
                          ast.FunctionDeclaration))

    def _parent_is_func_ref(self):
        # The second node is the parent node
        return isinstance(self._nodes_stack[-2], ast.FunctionReference)

    def visit_program(self, node):
        self.types = node.get_types()
        self.context = node.context
        children = node.children()
        for c in children:
            c.accept(self)
        if self.package:
            package_str = 'package ' + self.package + ';\n\n'
        else:
            package_str = ''
        self.ident = 2
        main_decls = [
            self.get_ident() + "static " + d.lstrip()
            for d in self._main_children]
        main_method = self.get_ident() + "static " + \
            self._main_method.lstrip() if self._main_method else None
        main_cls = "class Main {{\n{main_decls}{main_method}\n}}".format(
            main_decls="\n\n".join(main_decls),
            main_method="\n\n" + main_method if main_method else ""
        )
        other_classes = "\n\n".join(self.pop_children_res(children))
        self.program = "{package}{main}{f_interfaces}{other_classes}".format(
            package=package_str,
            main=main_cls,
            f_interfaces=self._get_functional_interfaces(),
            other_classes="\n\n" + other_classes if other_classes else ''
        )
        self._reset_state()

    @append_to
    def visit_block(self, node):
        children = node.children()
        is_func_non_void_block = self.is_func_non_void_block
        is_nested_func_block = self.is_nested_func_block
        self.is_func_non_void_block = False
        self.is_nested_func_block = False
        children_len = len(children)
        for i, c in enumerate(children):
            # Cast return statement if it's a number literal
            if i == children_len - 1:
                prev_cast_number = self._cast_number
                self._cast_number = True
                c.accept(self)
                self._cast_number = prev_cast_number
            else:
                c.accept(self)
        children_res = self.pop_children_res(children)
        self.is_func_non_void_block = is_func_non_void_block
        self.is_nested_func_block = is_nested_func_block

        return_stmt = "\n" + self.get_ident()
        sugar = ""
        sugar_semi = ""
        # We are in a block that will be added in a lambda and called in the
        # same statement. Hence we must return something to the lambda.
        if not self._parent_is_function():
            if not children:
                return_stmt += "return null;"
            elif isinstance(tu.get_type_hint(children[-1],
                                             self.context,
                                             self._namespace,
                                             jt.JavaBuiltinFactory(),
                                             self.types), jt.VoidType):
                if not isinstance(children[-1],
                               (ast.VariableDeclaration,
                                ast.FunctionCall,
                                ast.Assignment)):
                    sugar = "Object x_{x} = ".format(x=self._x_counter)
                    self._x_counter += 1
                return_stmt += "return null;"
            else:
                assert not isinstance(children[-1], ast.VariableDeclaration), \
                    ("We can't have VariableDeclaration as the last statement "
                     "in a Block")
                sugar = "return "
        # non-void function
        elif self.is_func_non_void_block:
            sugar = "return "
        # void function
        else:
            # We use this return statement if the function type is Void
            if self.is_nested_func_block:
                return_stmt += "return null;"
            # If return type is void, then we assign the last statement (except
            # var decl calls) in a variable x and then we use return_stmt.
            if (children and
                    not isinstance(children[-1],
                                   (ast.VariableDeclaration,
                                    ast.FunctionCall,
                                    ast.Assignment))):
                is_bottom = children[-1].is_bottom()
                type_hint = tu.get_type_hint(children[-1],
                                             self.context,
                                             self._namespace,
                                             jt.JavaBuiltinFactory(),
                                             self.types,
                                             smart_casts=self.smart_casts)
                is_lambda = (getattr(
                    type_hint, 'is_function_type', lambda: False)())

                if is_bottom:
                    var_prefix = 'Object'
                elif is_lambda:
                    var_prefix = self.get_type_name(type_hint)
                    if isinstance(children[-1], ast.Lambda):
                        sugar_semi = ";"
                elif isinstance(children[-1], ast.FunctionReference):
                    sig = tu.get_function_reference_type(
                        children[-1], self.context, self._namespace,
                        jt.JavaBuiltinFactory(), self.types,
                        smart_casts=self.smart_casts
                    )
                    sig = self.get_type_name(sig, True, True)
                    var_prefix = sig if sig else 'var'
                else:
                    var_prefix = 'Object'
                sugar = "{p} x_{x} = ".format(p=var_prefix, x=self._x_counter)
                return_stmt += ';' if is_lambda and not return_stmt.strip() \
                    else ''
                self._x_counter += 1

        # A block could be the body of a function or the body of an if statement
        if len(children_res) == 0:  # empty block
            res = "{{ {ret}{old_ident}}}".format(
                ret=return_stmt,
                old_ident=self.get_ident(extra=-2)
            )
        elif len(children_res) == 1:  # single statement
            children_res[0] = ut.add_string_at(
                children_res[0],
                sugar,
                ut.leading_spaces(children_res[0])) + sugar_semi
            res = "{{\n{ident}{stmt}{ret}\n{old_ident}}}".format(
                ident=self.get_ident(),
                stmt=children_res[0].strip(),
                ret=return_stmt,
                old_ident=self.get_ident(extra=-2)
            )
        else:
            children_res[-1] = ut.add_string_at(
                children_res[-1],
                sugar,
                ut.leading_spaces(children_res[-1])) + sugar_semi
            res = "{{\n{stmts}{ret}\n{old_ident}}}".format(
                stmts="\n".join(children_res),
                ret=return_stmt,
                old_ident=self.get_ident(extra=-2)
            )
        if not self._parent_is_function():
            etype = jt.Void
            if len(children) > 0:
                etype = tu.get_type_hint(children[-1],
                                         self.context,
                                         self._namespace,
                                         jt.JavaBuiltinFactory(),
                                         self.types,
                                         smart_casts=self.smart_casts)
            etype_str = self.get_type_name(etype, get_boxed_void=True)
            etype_str = PRIMITIVES_TO_BOXED.get(etype_str, etype_str)
            res = "((Function0<{etype}>) (() -> {res})).apply()".format(
                etype=etype_str,
                res=res
            )
        return res

    @append_to
    def visit_call_argument(self, node):
        old_ident = self.ident
        self.ident = 0
        children = node.children()
        for c in node.children():
            c.accept(self)
        self.ident = old_ident
        children_res = self.pop_children_res(children)
        return children_res[0]

    @append_to
    def visit_bottom_constant(self, node):
        return self.get_ident() + "{}{}null{}{}".format(
            '(' if self._parent_is_func_ref() else '',
            (
                '(' + self.get_type_name(node.t) + ') '
                if node.t and node.t != tp.Nothing
                else ''
            ),
            ')' if self._parent_is_func_ref() else '',
            ';' if self._parent_is_block() else ''
        )

    @append_to
    def visit_super_instantiation(self, node):
        return self.get_type_name(node.class_type)

    @append_to
    @change_namespace
    def visit_class_decl(self, node):
        def get_superclasses_interfaces():
            # In correct programs len(superclasses) must be at most 1.
            superclasses = []
            interfaces = []
            for cls_inst in node.superclasses:
                cls_name = cls_inst.class_type.name
                cls_inst = self.get_type_name(cls_inst.class_type)
                cls_decl = self.context.get_classes(
                    self._namespace, glob=True)[cls_name]
                if cls_decl.class_type == ast.ClassDeclaration.INTERFACE:
                    interfaces.append(cls_inst)
                else:
                    superclasses.append(cls_inst)
            return superclasses, interfaces

        def get_constructor_params():
            constructor_fields = OrderedDict()
            for field in node.fields:
                constructor_fields[field.name] = self.get_type_name(
                    field.field_type)
            return constructor_fields

        def construct_constructor():
            params = [tname + ' ' + name
                      for name, tname in
                      get_constructor_params().items()]
            constructor_params = ",".join(params)

            fields = ["this." + f.name + ' = ' + f.name + ";"
                      for f in node.fields]
            constructor_fields = "\n" + self.get_ident(extra=2) if fields \
                else ""
            constructor_fields += ("\n" + self.get_ident(extra=2)).join(fields)

            super_call = ""
            if node.superclasses:
                supercls = node.superclasses[0]
                if not isinstance(supercls.class_type, tp.Builtin):
                    res = ""
                    if supercls.args:
                        translator = JavaTranslator()
                        translator.context = self.context
                        translator._cast_number = True
                        translator._namespace = self._namespace
                        for expr in supercls.args:
                            translator.visit(expr)
                        res = translator._children_res
                        for expr, r in zip(supercls.args, res):
                            if isinstance(expr, ast.Lambda):
                                r = "({cast}) {lmd}".format(
                                    cast=self.get_type_name(expr.signature),
                                    lmd=r
                                )
                        res = ", ".join(res)
                        res = re.sub(r'\s+',' ',res)
                    super_call = "\n" + self.get_ident(extra=2) + 'super(' + \
                        res + ");"
            return ("{ident}public {name}({params}) {{{super_call}{fields}"
                    "{new_line}{close_ident}}}").format(
                ident=self.get_ident(),
                name=node.name,
                params=constructor_params,
                super_call=super_call,
                fields=constructor_fields,
                new_line="\n",
                close_ident=self.get_ident() if fields else ""
            )

        old_ident = self.ident
        self.ident += 2
        children = node.children()
        for c in children:
            c.accept(self)
        children_res = self.pop_children_res(children)
        field_res = [children_res[i]
                     for i, _ in enumerate(node.fields)]
        len_fields = len(field_res)
        len_supercls = len(node.superclasses)
        function_res = [children_res[i + len_fields + len_supercls]
                        for i, _ in enumerate(node.functions)]
        len_functions = len(function_res)
        type_parameters_res = ", ".join(
            children_res[len_fields + len_supercls + len_functions:])
        prefix = " " * old_ident
        prefix += (
            "final "
            if node.is_final else ""
        )
        res = "{}{} {}".format(prefix, node.get_class_prefix(), node.name)
        if type_parameters_res:
            res = "{}<{}>".format(res, type_parameters_res)
        superclasses, interfaces = get_superclasses_interfaces()
        if superclasses:
            res += " extends " + ", ".join(superclasses)
        if interfaces:
            if node.class_type == ast.ClassDeclaration.INTERFACE:
                # len(interfaces) should not be more than 1.
                res += " extends " + ", ".join(interfaces)
            else:
                res += " implements " + ", ".join(interfaces)
        body = " {"
        if function_res or field_res or superclasses:
            body += "\n"
            join_separator = "\n" + self.get_ident()
            if field_res:
                body += self.get_ident()
                body += join_separator.join(field_res)
                body += "\n\n"
            if superclasses or field_res:
                body += construct_constructor()
                if function_res:
                    body += "\n\n"
            if function_res:
                body += "\n\n".join(function_res)
            body += "\n" + self.get_ident(extra=-4) + "}"
        else:
            body += "}"
        res += body
        self.ident = old_ident
        return res

    @append_to
    def visit_type_param(self, node):
        bound = node.bound if node.bound is not None else ''
        if bound:
            bound_str = self.get_type_name(bound)
            bound = ' extends ' + PRIMITIVES_TO_BOXED.get(bound_str, bound_str)
        return "{name}{bound}".format(
            name=node.name,
            bound=bound
        )

    @append_to
    def visit_var_decl(self, node):
        prev_cast_number = self._cast_number
        self._cast_number = True
        children = node.children()
        for c in children:
            c.accept(self)
        children_res = self.pop_children_res(children)
        # NOTE Consider the following when using var inference
        # Global variables declared as fields in Main, thus we must specify
        # their type.
        #
        # We should also declare the type when a variable is an Object.
        # The following example does not compile if we don't:
        #
        # var foo = 'B'
        # if (foo == new Object()) {...}
        #
        # Finally, Function Types cannot be inferred.

        var_type = self.get_type_name(node.inferred_type)
        main_prefix = self._get_main_prefix('vars', node.name) \
            if self._namespace != ast.GLOBAL_NAMESPACE else ""
        expr = children_res[0].lstrip()
        res = "{ident}{final}{var_type} {main_prefix}{name} = {expr};".format(
            ident=self.get_ident(),
            final="final " if node.is_final else "",
            var_type=var_type,
            main_prefix=main_prefix,
            name=node.name,
            expr=expr
        )
        self._cast_number = prev_cast_number
        return res

    @append_to
    def visit_field_decl(self, node):
        return "public {final}{field_type} {name};".format(
            final="final " if node.is_final else "",
            field_type=self.get_type_name(node.field_type),
            name=node.name
        )

    @append_to
    def visit_param_decl(self, node):
        vararg_str = '...' if node.vararg else ''
        # Recall that varargs ara actually arrays in the signature of
        # the corresponding parameters.
        param_type = (
            node.param_type.type_args[0]
            if node.vararg and isinstance(node.param_type, tp.ParameterizedType)
            else node.param_type)
        res = self.get_type_name(param_type) + vararg_str + " " + node.name
        return res

    @append_to
    @change_namespace
    def visit_func_decl(self, node):
        def is_nested_func():
            parent_namespace = self._namespace[:-2]
            parent_name = self._namespace[-2]
            parent_decl = self.context.get_decl(parent_namespace, parent_name)
            if parent_decl is None:
                parent_decl = self.context.get_lambda(parent_namespace,
                                                      parent_name)
            is_func = isinstance(parent_decl, (ast.Lambda,
                                               ast.FunctionDeclaration))
            return is_func or (parent_name in ['true_block', 'false_block'])

        if self._inside_is:
            prev_inside_is_function = self._inside_is_function
            self._inside_is_function = True
        old_ident = self.ident
        if (self._namespace[-2],) == ast.GLOBAL_NAMESPACE:
            old_ident += 2
            self.ident += 2
        self.ident += 2
        prev_cast_number = self._cast_number
        children = node.children()
        is_func_non_void_block = self.is_func_non_void_block
        self.is_func_non_void_block = node.get_type() != jt.Void
        is_nested_func_block = self.is_nested_func_block
        self.is_nested_func_block = is_nested_func()
        is_expression = not isinstance(node.body, ast.Block)
        if is_expression:
            self._cast_number = True
        for c in children:
            c.accept(self)
        children_res = self.pop_children_res(children)
        len_params = len(node.params)
        len_type_params = len(node.type_parameters)
        param_res = [children_res[i] for i, _ in enumerate(node.params)]
        type_parameters_res = ", ".join(
            children_res[len_params:len_type_params + len_params])
        body_res = children_res[-1] if node.body else ''
        body = ""
        if body_res:
            if is_expression:
                if node.get_type() != jt.Void:
                    body_res = ut.add_string_at(
                        body_res, "return ", ut.leading_spaces(body_res))
                body = "{{\n{body};\n{ident}}}".format(
                    body=body_res,
                    ident=self.get_ident(old_ident=old_ident)
                )
            else:
                body = body_res
        if is_nested_func():
            types = list(map(lambda x: x.rsplit(' ', 1)[0], param_res))
            # Convert vararg to array
            types = list(map(lambda x: x.replace('...', '[]'), types))
            types.append(self.get_type_name(node.inferred_type, True))
            types = list(map(
                lambda x: PRIMITIVES_TO_BOXED.get(x, x), types))
            params = list(map(lambda x: x.split()[-1], param_res))
            self._function_interfaces.add(len(params))
            res_t = "{ident}Function{n}<{tp}> {name} = ({params}) -> {body};"
            res = res_t.format(
                ident=self.get_ident(old_ident=old_ident),
                n=len(params),
                tp=", ".join(types),
                name=node.name,
                params=", ".join(params),
                body=body
            )
        else:
            res = ("{ident}{public}{final}{abstract}{type_params}{ret_type} "
                   "{name}({params}) {body}{semicolon}").format(
                ident=self.get_ident(old_ident=old_ident),
                public="public ",
                final="final " if node.is_final else "",
                abstract="abstract " if body == "" else "",
                type_params=(
                    "<" + type_parameters_res + "> "
                    if type_parameters_res else ""
                ),
                ret_type=self.get_type_name(node.inferred_type),
                name=node.name,
                params=", ".join(param_res),
                body=body,
                semicolon=";" if body == "" else ""
            )
        if (self._namespace[-2],) == ast.GLOBAL_NAMESPACE:
            old_ident -= 2
        self.ident = old_ident
        self.is_func_non_void_block = is_func_non_void_block
        self.is_nested_func_block = is_nested_func_block
        self._cast_number = prev_cast_number
        if self._inside_is:
            self._inside_is_function = prev_inside_is_function
        return res

    @append_to
    @change_namespace
    def visit_lambda(self, node):
        if self._inside_is:
            prev_inside_is_function = self._inside_is_function
            self._inside_is_function = True
        old_ident = self.ident
        if (self._namespace[-2],) == ast.GLOBAL_NAMESPACE:
            old_ident += 2
            self.ident += 2
        self.ident += 2
        prev_cast_number = self._cast_number
        children = node.children()

        is_func_non_void_block = self.is_func_non_void_block
        self.is_func_non_void_block = node.get_type() != jt.Void

        is_expression = not isinstance(node.body, ast.Block)
        if is_expression:
            self._cast_number = True

        for c in children:
            c.accept(self)
        children_res = self.pop_children_res(children)
        param_res = [children_res[i] for i, _ in enumerate(node.params)]

        body_res = children_res[-1] if node.body else ''
        body = ""
        if body_res:
            if is_expression:
                if node.get_type() != jt.Void:
                    body_res = ut.add_string_at(
                        body_res, "return ", ut.leading_spaces(body_res))
                body = "{{{body};}}{semicolon}".format(
                    body=body_res,
                    semicolon=";" if self._parent_is_block() else ""
                )
            else:
                body = body_res

        res = "({params}) -> {body}".format(
            params=", ".join(param_res),
            body=body
        )

        if (self._namespace[-2],) == ast.GLOBAL_NAMESPACE:
            old_ident -= 2
        self.ident = old_ident
        self.is_func_non_void_block = is_func_non_void_block
        self._cast_number = prev_cast_number
        if self._inside_is:
            self._inside_is_function = prev_inside_is_function
        return res

    @append_to
    def visit_integer_constant(self, node):
        def get_cast_literal(integer_type, literal):
            if integer_type == jt.Long:
                return "(long)" + str(literal)
            if integer_type == jt.Short:
                return "(short)" + str(literal)
            if integer_type == jt.Byte:
                return "(byte)" + str(literal)
            if integer_type == jt.Number:
                return "(Number) new Long(" + str(literal) + ")"
            return str(literal)

        if not self._cast_number:
            return "{ident}{literal}{semicolon}".format(
                ident=self.get_ident(),
                literal=str(node.literal),
                semicolon=";" if self._parent_is_block() else ""
            )
        return "{ident}{cast_literal}{semicolon}".format(
            ident=self.get_ident(),
            cast_literal=get_cast_literal(node.integer_type, node.literal),
            semicolon=";" if self._parent_is_block() else ""
        )

    @append_to
    def visit_real_constant(self, node):
        def get_cast_literal(real_type, literal):
            if real_type == jt.Float:
                return "(float)" + str(literal)
            if real_type == jt.Number:
                return "(Number) new Double(" + str(literal) + ")"
            return str(literal)

        if not self._cast_number:
            return "{ident}{literal}{semicolon}".format(
                ident=self.get_ident(),
                literal=str(node.literal),
                semicolon=";" if self._parent_is_block() else ""
            )
        return "{ident}{cast_literal}{semicolon}".format(
            ident=self.get_ident(),
            cast_literal=get_cast_literal(node.real_type, node.literal),
            semicolon=";" if self._parent_is_block() else ""
        )

    @append_to
    def visit_char_constant(self, node):
        return "{ident} '{literal}'{semicolon}".format(
            ident=self.get_ident(),
            literal=node.literal,
            semicolon=";" if self._parent_is_block() else ""
        )

    @append_to
    def visit_string_constant(self, node):
        return "{ident}\"{literal}\"{semicolon}".format(
            ident=self.get_ident(),
            literal=node.literal,
            semicolon=";" if self._parent_is_block() else ""
        )

    @append_to
    def visit_boolean_constant(self, node):
        return "{ident}{literal}{semicolon}".format(
            ident=self.get_ident(),
            literal=str(node.literal),
            semicolon=";" if self._parent_is_block() else ""
        )

    @append_to
    def visit_array_expr(self, node):
        if not node.length:
            new_stmt = "new {etype}".format(
                etype=self.get_type_name(node.array_type.type_args[0])
            )
            if isinstance(node.array_type.type_args[0], tp.ParameterizedType):
                new_stmt = "({etype}[]) new Object".format(
                    etype=self.get_type_name(node.array_type.type_args[0])
                )

            return "{ident}{new}[0]{semicolon}".format(
                ident=self.get_ident(),
                new=new_stmt,
                semicolon=";" if self._parent_is_block() else ""
            )
        old_ident = self.ident
        prev_cast_number = self._cast_number
        self._cast_number = True
        self.ident = 0
        children = node.children()
        for c in children:
            c.accept(self)
        children_res = self.pop_children_res(children)

        if (isinstance(node.array_type, tp.ParameterizedType) and
                not node.array_type.type_args[0].is_primitive()):
            new_stmt = "({etype}) new Object[]".format(
                etype=self.get_type_name(node.array_type)
            )
        else:
            new_stmt = "new {etype}".format(
                etype=self.get_type_name(node.array_type)
            )

        self._cast_number = prev_cast_number
        self.ident = old_ident
        return "{ident}{new}{{{exprs}}}{semicolon}".format(
            ident=self.get_ident(),
            exprs=", ".join(children_res),
            new=new_stmt,
            semicolon=";" if self._parent_is_block() else ""
        )

    @append_to
    def visit_variable(self, node):
        return "{ident}{main_prefix}{name}{is_prefix}{semicolon}".format(
            ident=self.get_ident(),
            main_prefix=self._get_main_prefix('vars', node.name),
            name=node.name,
            is_prefix=self._visit_is_stack.count(node.name) * "_is",
            semicolon=";" if self._parent_is_block() else ""
        )

    @append_to
    def visit_binary_op(self, node):
        old_ident = self.ident
        self.ident = 0
        children = node.children()
        for c in children:
            c.accept(self)
        children_res = self.pop_children_res(children)
        res = "{ident}({left} {operator} {right}){semicolon}".format(
            ident=self.get_ident(old_ident=old_ident),
            left=children_res[0],
            operator=node.operator,
            right=children_res[1],
            semicolon=";" if self._parent_is_block() else ""
        )
        self.ident = old_ident
        return res

    def visit_logical_expr(self, node):
        self.visit_binary_op(node)

    def visit_equality_expr(self, node):
        self.visit_binary_op(node)

    def visit_comparison_expr(self, node):
        self.visit_binary_op(node)

    def visit_arith_expr(self, node):
        self.visit_binary_op(node)

    @append_to
    def visit_conditional(self, node):
        prev_inside_is = self._inside_is
        self._inside_is = True
        old_ident = self.ident
        self.ident += 2
        children = node.children()

        # Visit children
        cond = children[0]
        cond.accept(self)
        true_branch = children[1]
        false_branch = children[2]
        # Handle Smart Cast and is suffix
        prev_namespace = self._namespace
        if isinstance(cond, ast.Is):
            # true branch smart cast
            if not cond.operator.is_not:
                self._namespace = prev_namespace + ('true_block',)
                self.smart_casts.append((cond.lexpr, cond.rexpr))
                true_branch.accept(self)
                self.smart_casts.pop()
                self._visit_is_stack.pop()
                self._namespace = prev_namespace + ('false_block',)
                false_branch.accept(self)
            # false branch smart cast
            else:
                self._namespace = prev_namespace + ('true_block',)
                self._visit_is_stack.pop()
                true_branch.accept(self)
                self._namespace = prev_namespace + ('false_block',)
                self.smart_casts.append((cond.lexpr, cond.rexpr))
                false_branch.accept(self)
                self.smart_casts.pop()
        else:
            true_branch.accept(self)
            false_branch.accept(self)

        children_res = self.pop_children_res(children)
        res = "{ident}(({if_condition}) ?\n{body} : \n {else_body}){semicolon}".format(
            ident=self.get_ident(old_ident=old_ident),
            if_condition=children_res[0].lstrip(),
            body=children_res[1],
            else_body=children_res[2],
            semicolon=";" if self._parent_is_block() else ""
        )
        self.ident = old_ident
        self._inside_is = prev_inside_is
        self._namespace = prev_namespace
        return res

    @append_to
    def visit_is(self, node):
        old_ident = self.ident
        self.ident = 0

        is_variable = False
        if isinstance(node.lexpr, ast.Variable):
            is_variable = True

        children = node.children()
        children[0].accept(self)
        if is_variable:
            self._visit_is_stack.append(node.lexpr.name)
        for c in children[1:]:
            c.accept(self)
        children_res = self.pop_children_res(children)

        not_1 = "!(" if node.operator.is_not else ""
        not_2 = ")" if node.operator.is_not else ""
        new_var = " {name}{suffix}".format(
                name=node.lexpr.name,
                suffix=self._visit_is_stack.count(node.lexpr.name) * "_is"
            ) if is_variable else ""
        res = "{ident}{not_1}{expr} instanceof {type_to_check}{new}{not_2}".format(
            ident=self.get_ident(old_ident=old_ident),
            not_1=not_1,
            expr=children_res[0],
            type_to_check=node.rexpr.get_name(),
            new=new_var,
            not_2=not_2)
        self.ident = old_ident
        return res

    @append_to
    def visit_new(self, node):
        old_ident = self.ident
        self.ident = 0
        prev_cast_number = self._cast_number
        self._cast_number = True
        children = node.children()
        for c in children:
            c.accept(self)
        children_res = self.pop_children_res(children)
        self.ident = old_ident
        # Remove type arguments from Parameterized Type
        if getattr(node.class_type, 'can_infer_type_args', None) is True:
            cls = node.class_type.name + "<>"
        else:
            cls = self.get_type_name(node.class_type)
        res = "{ident}new {cls}({args}){semicolon}".format(
            ident=self.get_ident(),
            cls=cls,
            args=", ".join(children_res),
            semicolon=";" if self._parent_is_block() else ""
        )
        self._cast_number = prev_cast_number
        return res

    @append_to
    def visit_field_access(self, node):
        old_ident = self.ident
        self.ident = 0
        children = node.children()
        for c in children:
            c.accept(self)
        children_res = self.pop_children_res(children)
        self.ident = old_ident
        receiver = (
            '({})'.format(children_res[0])
            if isinstance(node.expr, ast.BottomConstant)
            else children_res[0]
        )
        return "{ident}{expr}.{field}{semicolon}".format(
            ident=self.get_ident(),
            expr=receiver,
            field=node.field,
            semicolon=";" if self._parent_is_block() else ""
        )

    @append_to
    def visit_func_ref(self, node):
        old_ident = self.ident

        self.ident = 0
        children = node.children()
        for c in children:
            c.accept(self)

        self.ident = old_ident

        children_res = self.pop_children_res(children)

        # Set receiver
        if children_res:
            receiver = children_res[0]
        else:
            # Global function
            receiver = ""
            # Use `this` if its a method within current class
            parent_cls = self.context.get_parent_class(self._namespace)
            if parent_cls:
                class_decls = self.context.get_classes(
                    ('global',), glob=True).values()
                parent_methods = parent_cls.get_callable_functions(class_decls)
                if node.func in {m.name for m in parent_methods}:
                    receiver = "this"
            # Do not use a receiver if its a variable (lambda case)
            decl = get_decl(self.context, self._namespace, node.func)
            if decl:
                namespace, decl = decl
                if namespace == ast.GLOBAL_NAMESPACE and isinstance(
                        decl, ast.FunctionDeclaration):
                    receiver = "Main"

        receiver += "::" if receiver != "" else ""

        res = "{ident}{receiver}{name}{semicolon}".format(
            ident=self.get_ident(),
            receiver=receiver,
            name=node.func,
            semicolon=";" if self._parent_is_block() else ""
        )
        return res

    @append_to
    def visit_func_call(self, node):
        def is_nested_func():
            # fdecl[0][-1] is the parent.
            if fdecl and fdecl[0][-1] != 'global' and fdecl[0][-1][0].islower():
                return True
            return False
        old_ident = self.ident
        self.ident = 0
        prev_cast_number = self._cast_number
        self._cast_number = True

        children = node.children()
        for c in children:
            c.accept(self)

        self.ident = old_ident

        # From where we are in the AST we search backwards for declarations
        # with the same name.
        fdecl = get_decl(self.context, self._namespace, node.func)
        if fdecl and not isinstance(fdecl[1], ast.FunctionDeclaration):
            fdecl = None

        children_res = self.pop_children_res(children)
        func = self._get_main_prefix('funcs', node.func) + node.func
        receiver = children_res[0] if node.receiver else None
        args = children_res[1:] if node.receiver else children_res
        # In case of a nested class with vararg as the last parameter,
        # we have to create an array with the vararg arguments.
        if (is_nested_func() and len(fdecl[1].params) > 0 and
                fdecl[1].params[-1].vararg):
            varargs = args[len(fdecl[1].params)-1:]
            varargs_type = fdecl[1].params[-1].param_type
            if not varargs_type.type_args[0].is_primitive():
                new_stmt = "({etype}) new Object[]".format(
                    etype=self.get_type_name(varargs_type)
                )
            else:
                new_stmt = "new {etype}".format(
                    etype=self.get_type_name(varargs_type)
                )
            varargs = "{new}{{{args}}}".format(
                new=new_stmt,
                args=", ".join(varargs)
            )
            args = args[:len(fdecl[1].params)-1] + [varargs]
        if receiver:
            receiver_expr = (
                '({}).'.format(children_res[0])
                if isinstance(node.receiver, ast.BottomConstant)
                else children_res[0] + '.'
            )
        else:
            receiver_expr = ''
        res = "{ident}{main}{receiver}{name}{apply}({args}){semicolon}".format(
            ident=self.get_ident(),
            main=self._get_main_prefix('vars', node.func) if node.is_ref_call \
                else "",
            receiver=receiver_expr,
            name=func,
            apply=".apply" if is_nested_func() or node.is_ref_call else "",
            args=", ".join(args),
            semicolon=";" if self._parent_is_block() else ""
        )
        self._cast_number = prev_cast_number
        return res

    @append_to
    def visit_assign(self, node):
        old_ident = self.ident
        self.ident = 0
        prev_cast_number = self._cast_number
        self._cast_number = True
        children = node.children()
        for c in children:
            c.accept(self)
        self.ident = old_ident
        children_res = self.pop_children_res(children)
        name = self._get_main_prefix('vars', node.name) + node.name
        receiver = children_res[0] if node.receiver else None
        expr = children_res[1] if node.receiver else children_res[0]
        if receiver:
            receiver_expr = (
                '({}).'.format(children_res[0])
                if isinstance(node.receiver, ast.BottomConstant)
                else children_res[0] + '.'
            )
        else:
            receiver_expr = ''
        res = "{ident}{receiver}{name} = {expr};".format(
            ident=self.get_ident(old_ident=old_ident),
            receiver=receiver_expr,
            name=name,
            expr=expr
        )
        self.ident = old_ident
        self._cast_number = prev_cast_number
        return res
